spring.application.name=financial-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/financial_tracker
spring.datasource.username=app
spring.datasource.password=app

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true